bash_command_green_taxi: "cd / && spark-submit --jars spark/jars/spark-avro_2.11-2.4.3.jar data_pipeline/etl_green_taxi.py"
bash_command_yellow_taxi: "cd / && spark-submit --jars spark/jars/spark-avro_2.11-2.4.3.jar data_pipeline/etl_yellow_taxi.py"
email: deniztaass@gmail.com