pipeline:
  data:
    # TODO(deniztas): Test this with 36 months if you have internet
    retention_N_months: 1
    schema_file: 'schema.yaml'
    output_parquet_dir: D:\nyc-taxi-data-pipeline\output_parquet\
    output_avro_dir: D:\nyc-taxi-data-pipeline\output_avro\
