tables:
  green_tripdata:
    raw_data_path: D:\nyc-taxi-data-pipeline\raw_data_csv\green_tripdata_2018-01.csv
    output_path_parquet: D:\nyc-taxi-data-pipeline\output_parquet\green_tripdata_2018-01
    output_path_avro: D:\nyc-taxi-data-pipeline\output_avro\green_tripdata_2018-01
    schema:
      VendorID:
        type: int
      lpep_pickup_datetime:
        type: DateTime
      lpep_dropoff_datetime:
        type: DateTime
      store_and_fwd_flag:
        type: boolean
      RatecodeID:
        type: int
      PULocationID:
        type: int
      DOLocationID:
        type: int
      passenger_count:
        type: int
      trip_distance:
        type: float
      fare_amount:
        type: int
      extra:
        type: float
      mta_tax:
        type: float
      tip_amount:
        type: float
      tolls_amount:
        type: float      
      ehail_fee:
        type: float
      improvement_surcharge:
        type: float
      total_amount:
        type: float
      payment_type:
        type: int
      trip_type:
        type: int
  yellow_tripdata:
    raw_data_path:
    output_path_parquet:
    output_path_avro:
    schema:
      VendorID:
        type: int
      tpep_pickup_datetime:
        type: DateTime
      tpep_dropoff_datetime:
        type: DateTime
      store_and_fwd_flag:
        type: boolean
      RatecodeID:
        type: int
      PULocationID:
        type: int
      DOLocationID:
        type: int
      passenger_count:
        type: int
      trip_distance:
        type: float
      fare_amount:
        type: int
      extra:
        type: float
      mta_tax:
        type: float
      tip_amount:
        type: float
      tolls_amount:
        type: float
      improvement_surcharge:
        type: float
      total_amount:
        type: float
